name: Test Actions
on:
  workflow_dispatch:
  pull_request: []

jobs:
  install-singularity:
    name: Install with defaults
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install defaults
        uses: ./
  install-singularity-3-custom:
    name: Install with custom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install custom
        uses: ./
        with:
          singularity-version: 3.11.0
          go-version: 1.18.0
  install-singularity-4-custom:
    name: Install with custom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install custom
        uses: ./
        with:
          singularity-version: 4.0.1
          go-version: 1.20.0
