name: Test Actions
on:
  workflow_dispatch:
  pull_request: []

jobs:
  install-singuarity:
    name: Install with defaults
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install defaults
        uses: ./

  install-singuarity-custom:
    name: Install with custom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install custom
        uses: ./
        with:
          singularity-version: 4.0.0
          go-version: 1.21.0
